name: Build General Runtime Images

on:
  workflow_dispatch:

jobs:
  build_vf_images:
    name: Build VF Runtime Images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          path: patches
      - uses: actions/checkout@v3
        with:
          name: voiceflow/general-runtime
          path: main
      # Applying patch to this repo.
      - name: Applying patch
        run: |
          git apply ../patches/0001-feat-blog-local-api-work-with-multiple-vf.files.patch && \
          git apply ../patches/0002-update-Dockerfile.patch
        working-directory: main
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ghcr.io/${{ github.repository }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: main
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}